### ISSUE TITLE
Issue with file names containing spaces

### ISSUE THREAD

**Issue by matthias-feind** [junian/sharp-exiftool#1]
https://github.com/junian/SharpExifTool/blob/b44f6b6f4cd3a347f91dc0665bd6013316a7601a/src/SharpExifTool/ExifTool.cs#L118

Hi Junian, 
many thanks for your great library! Its exactly what I needed for my current hobby project, but unfortunatly it looks like this line here creates issues with filenames including spaces. The overload of `Execute` that is called here will split them of into multiple lines and `ExifTool` then cannot open the file.
Quickfix would be to call the other overload by simply changing this line to `Execute([filename]);`

Again thanks a lot.

**Comment by junian** [comment]
Hi @matthias-feind,

You were right, it's a bug. Fixing it soon. Thanks for bringing it up.

**Comment by junian** [comment]
Fixed here: https://www.nuget.org/packages/SharpExifTool/12.87.0.1

**Comment by matthias-feind** [comment]
Works! Thanks for quick fix!
